[package]
name = "sstable"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4"
anyhow = "1.0"
crc32fast = "1.3"
memtable = { path = "../memtable" }
bloom = { path = "../bloom" }

[dev-dependencies]
tempfile = "3"
