[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
memtable = { path = "../memtable" }
sstable = { path = "../sstable" }
wal = { path = "../wal" }
anyhow = "1.0"

[dev-dependencies]
tempfile = "3"

